"""Simple, explainable forecasting scaffolding on the Nixtla ecosystem."""

from nixtla_scaffold.data import load_forecast_dataset
from nixtla_scaffold.best_practices import best_practice_receipts
from nixtla_scaffold.byo_model import (
    BYO_MODEL_AUTOMATION_OUTPUT,
    BYO_MODEL_SCHEMA_VERSION,
    BYOModelComparisonResult,
    BYOModelIngestResult,
    BYOModelScoreResult,
    build_byo_model_automation_markdown,
    build_byo_model_automation_recommendations,
    ingest_byo_model_forecasts,
    load_byo_model_forecasts,
    write_byo_model_comparison,
    write_byo_model_ingest,
    write_byo_model_scores,
)
from nixtla_scaffold.connectors import ingest_query_result
from nixtla_scaffold.comparisons import (
    FORECAST_COMPARISON_SCHEMA_VERSION,
    ForecastComparisonResult,
    compare_forecasts,
    write_forecast_comparison,
)
from nixtla_scaffold.custom_models import CUSTOM_MODEL_SCHEMA_VERSION, append_custom_model_result, forecast_with_custom_model
from nixtla_scaffold.diagnostics import build_run_diagnostics
from nixtla_scaffold.external import (
    EXTERNAL_FORECAST_SCHEMA_VERSION,
    build_external_forecast_metadata,
    canonicalize_external_forecasts,
    load_external_forecasts,
)
from nixtla_scaffold.external_scoring import (
    EXTERNAL_SCORE_SCHEMA_VERSION,
    ExternalForecastScoreResult,
    score_external_forecasts,
    write_external_forecast_scores,
)
from nixtla_scaffold.experiments import (
    COMPARE_MODELS_SCHEMA_VERSION,
    EXPERIMENT_SCHEMA_VERSION,
    EXPERIMENT_VARIANTS,
    OPTIMIZER_SCHEMA_VERSION,
    ExperimentResult,
    OptimizerResult,
    compare_models,
    run_experiment,
    run_optimizer,
)
from nixtla_scaffold.challengers import (
    CHALLENGERS_SCHEMA_VERSION,
    ChallengerEngine,
    ChallengerForecasts,
    ChallengerSkip,
    available_challenger_engines,
    build_challenger_leaderboard,
    get_challenger_engine,
    register_challenger_engine,
    run_challengers,
)
from nixtla_scaffold.finn_bridge import (
    FINN_BRIDGE_SCHEMA_VERSION,
    FINNCheckResult,
    FINNComparisonResult,
    FINNRunResult,
    FINNScoreResult,
    canonicalize_finn_forecasts,
    check_finn_environment,
    compare_finn_forecasts,
    run_finn_bridge,
    score_finn_forecasts,
)
from nixtla_scaffold.forecast import run_forecast
from nixtla_scaffold.headline import ExecutiveHeadline, build_executive_headline
from nixtla_scaffold.hierarchy import aggregate_hierarchy_frame, hierarchy_coherence, hierarchy_summary, reconcile_hierarchy_forecast, reconcile_hierarchy_forecast_both
from nixtla_scaffold.knowledge import load_agent_skill
from nixtla_scaffold.ledger import (
    DEFAULT_LEDGER_PATH,
    LEDGER_SCHEMA_VERSION,
    LedgerResult,
    compare_versions,
    export_ledger,
    ingest_actuals,
    ingest_adjustments,
    init_ledger,
    lock_version,
    register_run,
)
from nixtla_scaffold.ops import (
    DOCTOR_SCHEMA_VERSION,
    DRIFT_SCHEMA_VERSION,
    OPERATE_SCHEMA_VERSION,
    RUN_RECEIPT_SCHEMA_VERSION,
    RUN_STATUS_SCHEMA_VERSION,
    VALIDATION_RECEIPT_SCHEMA_VERSION,
    build_doctor_payload,
    build_drift_payload,
    build_run_receipt,
    build_status_payload,
    build_validation_receipt,
    run_operating_loop,
    write_drift_report,
    write_operational_receipts,
)
from nixtla_scaffold.pipelines import PIPELINE_SCHEMA_VERSION, refresh_pipeline, run_pipeline
from nixtla_scaffold.presets import PRESET_NAMES, forecast_spec_preset, preset_catalog
from nixtla_scaffold.profile import profile_dataset
from nixtla_scaffold.release_gates import OPTIONAL_EXTRAS, ReleaseGateResult, format_release_gate_console_summary, run_release_gates
from nixtla_scaffold.reports import build_html_report, build_streamlit_app, write_report_artifacts
from nixtla_scaffold.scenario_lab import run_scenario_lab
from nixtla_scaffold.schema import (
    ChallengerSpec,
    CleaningSpec,
    CustomModelSpec,
    DataProfile,
    DriverEvent,
    EnsembleSpec,
    FeatureRecipeSpec,
    ForecastRun,
    ForecastSpec,
    KnownFutureRegressor,
    ParallelSpec,
    SeriesProfile,
    TransformSpec,
    forecast_spec_from_dict,
)
from nixtla_scaffold.setup import SetupAnswers, create_forecast_setup, setup_questions
from nixtla_scaffold.transformations import add_fiscal_calendar, apply_event_adjustments, label_anomalies, normalize_by_factor
from nixtla_scaffold.workbench_qa import GOLDEN_SCENARIOS, SCENARIO_ALIASES, SCENARIO_DESCRIPTIONS, WORKBENCH_QA_SCENARIOS, run_workbench_qa

__all__ = [
    "DataProfile",
    "ForecastRun",
    "ForecastSpec",
    "GOLDEN_SCENARIOS",
    "SCENARIO_ALIASES",
    "SCENARIO_DESCRIPTIONS",
    "WORKBENCH_QA_SCENARIOS",
    "PRESET_NAMES",
    "EXPERIMENT_VARIANTS",
    "OPTIONAL_EXTRAS",
    "ExecutiveHeadline",
    "EXTERNAL_FORECAST_SCHEMA_VERSION",
    "EXTERNAL_SCORE_SCHEMA_VERSION",
    "FORECAST_COMPARISON_SCHEMA_VERSION",
    "CUSTOM_MODEL_SCHEMA_VERSION",
    "COMPARE_MODELS_SCHEMA_VERSION",
    "EXPERIMENT_SCHEMA_VERSION",
    "OPTIMIZER_SCHEMA_VERSION",
    "LEDGER_SCHEMA_VERSION",
    "RUN_RECEIPT_SCHEMA_VERSION",
    "VALIDATION_RECEIPT_SCHEMA_VERSION",
    "RUN_STATUS_SCHEMA_VERSION",
    "DOCTOR_SCHEMA_VERSION",
    "DRIFT_SCHEMA_VERSION",
    "OPERATE_SCHEMA_VERSION",
    "PIPELINE_SCHEMA_VERSION",
    "BYO_MODEL_AUTOMATION_OUTPUT",
    "BYO_MODEL_SCHEMA_VERSION",
    "FINN_BRIDGE_SCHEMA_VERSION",
    "CustomModelSpec",
    "ChallengerSpec",
    "CHALLENGERS_SCHEMA_VERSION",
    "ChallengerEngine",
    "ChallengerForecasts",
    "ChallengerSkip",
    "available_challenger_engines",
    "build_challenger_leaderboard",
    "get_challenger_engine",
    "register_challenger_engine",
    "run_challengers",
    "CleaningSpec",
    "EnsembleSpec",
    "FeatureRecipeSpec",
    "ParallelSpec",
    "BYOModelComparisonResult",
    "BYOModelIngestResult",
    "BYOModelScoreResult",
    "ExternalForecastScoreResult",
    "ExperimentResult",
    "OptimizerResult",
    "ForecastComparisonResult",
    "FINNCheckResult",
    "FINNComparisonResult",
    "FINNRunResult",
    "FINNScoreResult",
    "LedgerResult",
    "ReleaseGateResult",
    "DriverEvent",
    "KnownFutureRegressor",
    "SeriesProfile",
    "SetupAnswers",
    "TransformSpec",
    "add_fiscal_calendar",
    "aggregate_hierarchy_frame",
    "apply_event_adjustments",
    "best_practice_receipts",
    "build_run_diagnostics",
    "build_run_receipt",
    "build_validation_receipt",
    "build_status_payload",
    "build_doctor_payload",
    "build_drift_payload",
    "build_external_forecast_metadata",
    "build_html_report",
    "build_executive_headline",
    "build_streamlit_app",
    "build_byo_model_automation_markdown",
    "build_byo_model_automation_recommendations",
    "append_custom_model_result",
    "compare_forecasts",
    "compare_finn_forecasts",
    "compare_models",
    "create_forecast_setup",
    "forecast_spec_preset",
    "forecast_spec_from_dict",
    "forecast_with_custom_model",
    "format_release_gate_console_summary",
    "hierarchy_coherence",
    "hierarchy_summary",
    "ingest_byo_model_forecasts",
    "ingest_query_result",
    "ingest_actuals",
    "ingest_adjustments",
    "init_ledger",
    "label_anomalies",
    "load_agent_skill",
    "load_forecast_dataset",
    "load_byo_model_forecasts",
    "load_external_forecasts",
    "canonicalize_external_forecasts",
    "canonicalize_finn_forecasts",
    "check_finn_environment",
    "normalize_by_factor",
    "profile_dataset",
    "preset_catalog",
    "reconcile_hierarchy_forecast",
    "reconcile_hierarchy_forecast_both",
    "register_run",
    "run_forecast",
    "run_experiment",
    "run_optimizer",
    "run_finn_bridge",
    "run_operating_loop",
    "run_pipeline",
    "refresh_pipeline",
    "run_release_gates",
    "run_scenario_lab",
    "run_workbench_qa",
    "score_external_forecasts",
    "score_finn_forecasts",
    "setup_questions",
    "write_external_forecast_scores",
    "write_byo_model_comparison",
    "write_byo_model_ingest",
    "write_byo_model_scores",
    "write_report_artifacts",
    "write_operational_receipts",
    "write_drift_report",
    "write_forecast_comparison",
    "lock_version",
    "compare_versions",
    "export_ledger",
    "DEFAULT_LEDGER_PATH",
]
